Add labeler and ci job to auto-merge Dependabot PRs (#49)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,3 +38,24 @@ jobs:
     if: ${{ needs.changes.outputs.container == 'true' }}
     needs: changes
     uses: ./.github/workflows/container.yml
+
+  all:
+    needs:
+     - changes
+     - container
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+    - name: Status summary
+      run: |
+        if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+          echo "One or more required jobs failed or were cancelled"
+          exit 1
+        else
+          echo "All jobs completed successfully"
+        fi
+
+  dependabot:
+    needs:
+      - all
+    uses: ./.github/workflows/dependabot.yml
